version: '1'
services:
  postgres:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: postgres
    image: data-catalog-postgres:0.1
    ports:
      - "5432:5432"
    volumes:
      - $DATA_CATALOG_SOLUTION_DATA/pgsql:/var/lib/pgsql
    #command: ["sh", "-c", "set -e;/entrypoint.sh"]
    command: ["tail", "-f", "/dev/null"]
