version: '1'
services:
  postgres:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: postgres
    image: data-catalog-postgres:$IMG_VERSION
    ports:
      - "5432:5432"
    volumes:
      - $DATA_CATALOG_SOLUTION_DATA/postgres/data:/var/lib/pgsql/14/data
      - /etc/hosts:/etc/hosts
    working_dir: /var/lib/pgsql/14/data
    command: ["sh", "-c", "set -e;/entrypoint.sh"]

